### ISSUE TITLE
Is the pool goroutine safe?

### ISSUE THREAD

**Issue by chenwenqiang** [ewohltman/pool#1]
I wonder that goroutines can use  an clientpool?

**Comment by ewohltman** [comment]
Sorry for the delay, in pool.go:

"PClients are safe for concurrent use by multiple goroutines."

That said, FYI, I wouldn't actually recommend using this pool lib as it is in real systems.  Consider it more of an interesting approach to share.  The upper bound semaphore doesn't really work, but the rate limiting does.
